### ISSUE TITLE
Get All Files from org - Results in "Retrieve Errors" and "package not found"

### ISSUE THREAD

**Issue by hasmanytrees** [celador/ForceCode#103]
When trying to retrieve all files from a sandbox org I end up getting a "Retrieve Errors" error in the status bar with a thumbs down next to it.  In the ForceCode Output I see lots of "Status: InProgress" lines followed by an error that simply says "package not found".  This org is relatively large with around 90% of the default 3 million characters of Apex being used.  I set my "pollTimeout" to 6000 in hopes to have better luck but it hasn't helped.  I used to be able to retrieve this org but it started failing after recent updates to ForceCode and VS Code.  Any help would be appreciated.

**Comment by hasmanytrees** [comment]
Anyone have any advice?  As it stands I can't use this wonderful tool as I can't download the source code from my org.

**Comment by celador** [comment]
If you can retrieve the package using workbench, that would be a good
starting point. You can use the tool from there.

The tool uses the same endpoint as the workbench, so YMMV.

Otherwise, it would be great if you could help debug the issue. There are
some directions near the end of the readme.

Another suggestion is to use the open file functionality and only download
the files you need to.

Let me know.
