### ISSUE TITLE
Not checking for changes on server.

### ISSUE THREAD

**Issue by LuciferDoCode** [celador/ForceCode#119]
When file on server is modified and is different on local machine.

**Expected : while saving file from local machine should warn with the message of different file content in server and local.
Actual result  : It is saving the changes of local to server without any warning and overriding the files on server.**

**Comment by ctinghino** [comment]
That's very critical

**Comment by iguerini** [comment]
This is something that is definitely needed.

**Comment by celador** [comment]
Would you like to help implement it?  It shouldn't be too difficult.  We simply need to retrieve the metadata info about every file in the org and match the last modified against the local version, if it's different, run the diff command and check if the contents are different, if they are, display a prompt asking for an overwrite, otherwise save the file.  

Would you like to take a shot at writing up the code for it?  

(I don't do Salesforce work anymore, so it would be super helpful if you could help me a bit with the development of this feature)

**Comment by jgomes94** [comment]
Hi @celador i am interested in developing this feature could you give some tips on where i should look for

Thanks
