### ISSUE TITLE
Single file refresh refreshes all files on local machine.

### ISSUE THREAD

**Issue by LuciferDoCode** [celador/ForceCode#120]
When refreshing a single file from server from the explorer, it refresh all the files. Checked in Case of Apex classes.

**Comment by amitkumarj1979** [comment]
This is another issue which i found as well. Line 163 in retrieve is not able to find the actual file where the user selected refresh, not sure about the regex expression. if you can review that and fix it.

**Comment by celador** [comment]
eek, thanks.  I'll look into that.

**Comment by doug-episource** [comment]
This bug seems to only affect Windows, but I have found a fix for it, and I cleaned up a couple of other minor issues during the retrieve. I see that you have said that this has been deprecated in favor of SalesforceDX, so I am not sure if you still are going to accept changes. Just in case, I am attaching the file, but if you would prefer a PR, just let me know.

With regards to your decision to deprecate this fantastic plugin, I really wish you wouldn't. SalesforceDX does not seem to work well for established teams that have been working with tools like gulp/grunt, git, and other IDEs to manage SF development. I get that SFDC wants us to all work the same way, but Scratch Orgs will not work for my team and just introduce another layer of difficulty.

[retrieve.ts.zip](https://github.com/celador/ForceCode/files/1396516/retrieve.ts.zip)

**Comment by doug-episource** [comment]
This bug seems to only affect Windows, and it is related to using "path.sep". The metadata path is platform independent and is the format "classes/class.cls", so you can just replace path.sep with "/". I see that you have said that this has been deprecated in favor of SalesforceDX, so I am not sure if you still are going to accept changes. If you still are, I can create a PR -- just let me know.

With regards to your decision to deprecate this fantastic plugin, I really wish you wouldn't. SalesforceDX does not seem to work well for established teams that have been working with tools like gulp/grunt, git, and other IDEs to manage SF development. I get that SFDC wants us to all work the same way, but Scratch Orgs will not work for my team and just introduce another layer of difficulty.
