### ISSUE TITLE
Refresh Not Pulling Standard Objects

### ISSUE THREAD

**Issue by colbybridges** [celador/ForceCode#146]
Hello,
I did a refresh to pull down our companies SFDC org onto my local but I'm not seeing Standard Objects in the src files. Am I missing a step?

**Comment by mnunezdm** [comment]
Is the same issue I have using the Ant Migration Tool, you have to specify all the standard objects in the custom object tag of the package.xml in order to retrieve them... Specifying only the wildcard just download the custom. I don't know if this is the expected behavior of Salesforce

The workaround I'm using is:

1. Retrieve all the org using ForceCode > retrieve package/metadata > retrieve all org
2. Manually add all the Standard Objects under the <members>*</members> like:
```xml
<types>
     <members>*</members>
     <members>Case</members>
     <members>Account</members>
      (.......)
     <name>Account</name>
<types>
```
3. Retrieve using ForceCode > retrieve package/metadata > retrieve by package xml

Miguel
