### ISSUE TITLE
Add Apex Documentation Command

### ISSUE THREAD

**Issue by no-stack-dub-sack** [celador/ForceCode#261]
**Is your feature request related to a problem? Please describe.**
There is no particular problem, however, it would be great to have an in-ForceCode way to document our .cls files.

**Describe the solution you'd like**
I stumbled upon the original [ApexDoc](https://github.com/SalesforceFoundation/ApexDoc/) a couple of months ago, but noticed it was no longer being supported, and feature requests / issues were not being addressed (which is fine, Salesforce acknowledged they would no longer be supporting the project). However, I thought there was still a need for something like this, and thought it might be fun to try to take it over. So I forked the repo [here ](https://github.com/no-stack-dub-sack/ApexDoc2) and began making some improvements and adding additional features. It's nearly ready (though I still haven't uploaded a release yet), and thought that a VSCode extension would be the best place for something like this.

Before creating a new extension, I thought I'd ask if there would be any interest in incorporating this here, as ForceCode seems well-established as the standard extension for SF dev in VSCode. I have a [basic POC](https://github.com/no-stack-dub-sack/ForceCode/pull/1/files) of how this might work if you'd like to take a look.

Unfortunately, the original ApexDoc was written in Java, and I've continued on this path, so for now it means adding the compiled jar file to the project, and calling it from there. I realize it would be much more ideal if the project were written in JS / TypeScript, and I have considered a re-write, but I think I would only consider taking on that level of effort if it seemed like there was actually some interest in the project. 

If there's any interest, please let me know what you think. I'm happy to discuss further.

**Comment by daishi4u** [comment]
Sorry I haven't had a chance to look into this quite yet. I like the idea, but I feel that in the long run it should be converted to typescript. I'll comment more when I get a chance to test it out.

**Comment by no-stack-dub-sack** [comment]
@daishi4u Thanks, and no worries. Keep me posted. I've just pushed a new commit which updates the config two new arguments: includes/excludes, so please check out the branch's latest. The updated documentation for these arguments is on the project's README.

**Comment by daishi4u** [comment]
Looks like it's working, but I noticed a few problems:
1. ApexDoc doesn't seem to like the scopes of testMethod and WebService
2. Any paths that you are creating should include path.sep or you can use path.join so it is OS agnostic
3. I would return the execSync command or find a way to include feedback to the user...it was quite the task to debug any output.
4. I wasn't able to find the documentation for the new options, so I referenced the ApexDoc documentation.

I would say if those issues are addressed, then you can pull in my dx-testing branch and merge. Then go ahead and make a pull request against dx-testing and I could get this into 3.16.0! :) I would also include that users need Java installed in the documentation as well in order to use it. I think most people will anyways so they can use Apex autocompletion from the Salesforce extension.

**Comment by no-stack-dub-sack** [comment]
Hey @daishi4u, thanks for the feedback! I will look into these issues, however, the more I thought about it, the more I agree that this really should be a TS project. I ended up translating it and making a few other improvements along the way (some of which address some of your concerns). Overall I think this will make it much easier to maintain as well.

It sounds like you're willing to make this a part of ForceCode, which is awesome! But now that it's a TS project, maybe we should think about how best to include this. Should the code be merged into the ForceCode base directly? Should it be installed as a separate dependency and maintained in it's own repo?

Currently, the TS project is being developed as an [independent extension](https://GitHub.com/no-stack-dub-sack/ApexDoc2-VSCode) (the latest hasn't been merged in yet, it's on a feature branch), but it would be pretty simple to get it merged into ForceCode. Maybe we can discuss options via chat at some point?

P.S. any new options should be documented directly on the README of the ApexDoc2 Java project, I will work on getting the README updated on the Vscode extension

**Comment by daishi4u** [comment]
@no-stack-dub-sack This is awesome news! Right off of the bat, I'm thinking that maybe, since you already have it set up as an independent extension, it could be on its own and also a plugin for Forcecode. I've been thinking on ways to code plugin functionality for Forcecode, and I think it could be as simple an an extension returning an object with an isForceCodePlugin property set to true, as well as data that would be shown in the menu. We could discuss further details at some point.

The easiest way to get ahold of me via chat would be to message me via the Forcecode slack group. Thanks for tackling this!

**Comment by no-stack-dub-sack** [comment]
Hey @daishi4u, thanks! Yeah, I was starting to think the same thing, as I've been building in some additional features (doc server, ApexDoc2 comment stubs / completion events, onEnterRules to better support block comments in Apex, etc.), enough where I think it could warrant being its own extension at this point, though I love the idea of being a ForceCode plugin. Would be happy to chat about that, and will hit you up on Slack at some point soon.

Thanks for helping to point this in the right direction!

**Comment by no-stack-dub-sack** [comment]
@daishi4u I think this can safely be closed unless there's been any progress on the plugin route, as the extension is finally published after eventually being re-written in TS and enhanced from the original quite a bit. It can be found [here](https://marketplace.visualstudio.com/items?itemName=PeterWeinberg.apexdox-vs-code&ssr=false#overview) if you or anyone else stumbling across this issue is interested!

Thanks!

**Comment by daishi4u** [comment]
Thank you, glad you were able to publish! I'll have to check it out!
