### ISSUE TITLE
Error while saving LWC with field definition imports

### ISSUE THREAD

**Issue by Radon7** [celador/ForceCode#269]
If in my LWC I have a custom field definition import the save yields an error. If I try to deploy via sfdx the same error does not appear.

`import CLOSING_REASON from '@salesforce/schema/Lead.ClosedReason__c'; `

On save the following error appears

> Invalid reference Lead.ClosedReason__c of type sobjectField in file myComponent.js

**Comment by daishi4u** [comment]
Have you by chance tried this with the 3.16.0-6 beta? I know I fixed a lot of deployment related bugs so it might also fix this as well.

**Comment by jonathanwiesel** [comment]
Also happening to me in 3.15.2 (pushed with SFDX and works).

If it's working in the beta, how can we update to the beta? 
Any timeframe when the stable release will be updated?

**Comment by daishi4u** [comment]
Interesting. This only happens with custom fields. You can deploy the lwc component as a whole by choosing the deploy package command from the ForceCode menu, then choose files and choose your lwc component and that will save. I'm assuming this is the route that the SFDX extension uses instead of updating each individual file like ForceCode does. I will dig deeper, but at the moment this seems to be on the Salesforce side of things

**Comment by daishi4u** [comment]
This is fixed in 3.16.0-8. You can download via the beta-testing channel in the Forcecode slack.

**Comment by jonathanwiesel** [comment]
In 3.16.0-8 it seems it compiles and saves, yet it doesn't since refreshing after doing so brings back the previous change.

**Comment by daishi4u** [comment]
Could I get the full source of your lwc zipped up and sent my way? During my testing it was definitely saving to the server, so I would like to see if something else is going on as well. If you don't want to share it here I can always provide my email or you can slack message me (Brett Wagner) on the Forcecode slack
