### ISSUE TITLE
Error when Save/Compile/Deploy Lightning Resource, it does not save to the server

### ISSUE THREAD

**Issue by rock-pile** [celador/ForceCode#30]
OS: Win 10
Error when attempting to Save/Compile/Deploy Lightning files.

`ForceCode: Unknown Tooling Type. Ensure the body is well formed`

**Comment by celador** [comment]
Did some rework on compile recently. Please try again and let me know.

**Comment by SkyLegend** [comment]
The issue still persists for lightning files with the latest version.
OS:Win 10

**Comment by rock-pile** [comment]
Confirmed, still exists with today's release.

**Comment by mgarf** [comment]
Confirm with Windows 10.

**Comment by mgarf** [comment]
Debugging Notes:

* getToolingType returns 'undefined' because match statement isn't working.
** Replace statement with below works: 

`    if (document.fileName.indexOf('src' + slash + 'aura') >= 0) {
        return 'AuraDefinition';
    }`

** New Error with forcecode compile failing...Currently debugging.

**Comment by rock-pile** [comment]
@celador Tested latest release, issue is still happening when attempting to save/deploy a lightning component file

ForceCode: Unknown Tooling Type. Ensure the body is well formed

**Comment by DougJod** [comment]
@mgarf 
Confirmed that your fix works on Windows 10:
in getToolingTypes.ts change
`if (document.fileName.match('src'+slash+'aura') ) {`
to
`if (document.fileName.indexOf('src' + slash + 'aura') >= 0) {`

and in getName.ts change
`var auraNameParts: string[] = (parts && parts.length) > 1 ? parts[1].split(new RegExp(slash)) : undefined;`
to
`    var auraNameParts: string[] = (slash == '\\')
        ? (parts && parts.length) > 1 ? parts[1].split(slash) : undefined  // windows path separator
        : (parts && parts.length) > 1 ? parts[1].split(new RegExp(slash)) : undefined;  // mac/linux path separator`

I wonder if 
'parts[1].split(slash)'
instead of 
'parts[1].split(new RegExp(slash))'
would work in linux/mac as well, then we wouldn't need the logic to check the path separator.
I can check on my linux box at home later, but can anyone test this on a mac?

**Comment by DougJod** [comment]
Looks like the split(slash) without the 'new RegExp(...)' works in Linux (Ubuntu 16.04) as well as WIndows 10. If someone can confirm that it's ok on a mac, then I'll get it ready for a Pull Request.

**Comment by celador** [comment]
Merged and closed

**Comment by rock-pile** [comment]
confirmed this is working now, thanks @DougJod  and @celador

**Comment by reyaustral** [comment]
Hi, I'm using v0.3.10 but I'm still encountering this error. I cannot locate the code that DougJod and mgarf provide. Windows OS 7 Enterprise 64 bit. Visual Studio Code 1.7.2 
Thanks and Regards,

**Comment by jdatskuid** [comment]
I'm getting this bug when trying to save a Static Resource. Let me know what information you want/need.
