### ISSUE TITLE
Encrypt force.json file

### ISSUE THREAD

**Issue by jtribley** [celador/ForceCode#32]
An idea to consider is to encrypt the Force.json file as it shows org logon credentials and passwords in plain text.

**Comment by celador** [comment]
I've toyed with this idea.  Used xKeychain previously and it turned out to be more of a pain than anything.  I've found it more useful to have the credentials easily available for use than any benefit I'd get from security.  Your machine is supposed to be secure.  If you don't want it in source control, ignore it.  You should be ignoring your personal settings anyway.

I might look into doing this again in the future, but it's no promise.  Thank you for the suggestion.  How do you like the extension otherwise?

**Comment by jtribley** [comment]
thanks for considering it.
I've only just starting using the extension/VS Code after The Welkin Suite moved to subscription. I'll let you know after I've used it more.
