### ISSUE TITLE
Possibilty for Lightning Message Service

### ISSUE THREAD

**Issue by jgallagants** [celador/ForceCode#333]
With the new Winter 20',  Salesforce has created a Message service to be able to send messages between components. 

Unluckily, I already need to use this service. Reading about how to create one, It seems that you need to deploy it with SFDX.

Could be possible to add this new feature to ForceCode to create and deploy Lightning Message Services?

Thank you very much.

**Comment by daishi4u** [comment]
This should already be supported. In order to use LMS, you need to make sure the org you're logged into has an apiVersion of 47.0. Once you have changed to 47.0, click save, then restart vscode and you'll have access to LMS:
![image](https://user-images.githubusercontent.com/6629523/68348341-45eaf100-00bf-11ea-9fd0-ad7877aea38c.png)
![image](https://user-images.githubusercontent.com/6629523/68348369-556a3a00-00bf-11ea-8afa-2ae40d894f49.png)
![image](https://user-images.githubusercontent.com/6629523/68348394-69ae3700-00bf-11ea-9f05-e7bdf3af3c9c.png)

**Comment by daishi4u** [comment]
Reopening, as I did find an issue while saving.

**Comment by daishi4u** [comment]
In order to save an LMS channel through Forcecode it will need to be in the messageChannels folder and have a .messageChannel extension:
![image](https://user-images.githubusercontent.com/6629523/68349862-25716580-00c4-11ea-95f5-8c69f2f383ba.png)
