### ISSUE TITLE
Lastest Update (0.2.31) breaks ForceCode menu

### ISSUE THREAD

**Issue by DougJod** [celador/ForceCode#42]
Can no longer access the ForceCode menu. I get the error:
`command 'ForceCode.showMenu' not found.`

**Comment by DougJod** [comment]
Looks like 0.2.32 fixed this.

**Comment by DougJod** [comment]
This is happening again.
VSCode version: 1.9.1
ForceCode version: 0.5.13

**Comment by rock-pile** [comment]
Running ForceCode 0.5.13 & VSCode 1.9.1 on Windows 10 and it is working fine for me, but I upgraded from previous versions.

Installed ForceCode 0.5.13 in a colleagues clean VSCode instance (also windows 10) and they are seeing the same issue.

This issues sounds related too..
https://github.com/celador/ForceCode/issues/77

**Comment by fuure** [comment]
I got it

Something not marked in the readme: ForceCode doesn't work properly if your Apex and Visualforce extensions aren't previously installed. Obviously you omitted this because you correctly handled this in your [package.json](https://github.com/celador/ForceCode/commit/df581df587c025ed313dd18d927b930a568494cf) file

However, the extension dependencies seems to be um... not working correctly, extensions aren't installing (At least on my vscode). My starting scenario was just Apex installed, then Forcecode, but no Visualforce. And I got the error.

So just install both extensions, reload, install ForceCode and problem solved.

**Comment by henko-okdev** [comment]
I have the save issue.
The flow described by @fuure didn't help me.
Do someone have any idea how it could be fixed/omitted?

**Comment by celador** [comment]
Check out your ~/.vscode/extensions folder. Clear out any forcecode apex or
visualforce extensions if they are there. Then reinstall the extensions,
installing apex and visualforce first.

**Comment by GrayChoi** [comment]
@celador I followed your instructions. But it didn't help me.

**Comment by celador** [comment]
Good catch! Thank you. I will update the file name.

**Comment by javansoliday** [comment]
I am getting this error as well. I have version 1.25.1 of VScode and 0.5.35 of Force Code.  I am using macOS Sierra version 10.12.6.

**Comment by trentchilders** [comment]
I'm still having this issue. So far I have downloaded the Java DK8 and set the user parameters as `"salesforcedx-vscode-apex.java.home" : "/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home"`. Then I uninstalled ForceCode and wiped the `extensions` directory of all apex and visualforce folders. Then reinstalled each of those individually then reinstalled ForceCode.

I still get the error. What did I miss here?
