### ISSUE TITLE
Show unit test coverage

### ISSUE THREAD

**Issue by dshahin** [celador/ForceCode#57]
As a developer I want to run all unit tests (or a subset) and provide a visual representation of which lines have code coverage.

- [ ] provide a way to select and run available unit tests
- [ ] show colored representation of covered vs uncovered code

**Comment by celador** [comment]
Test for the current file can be run with the Run Tests command
Tests for the org can be run with the Deploy command, by selecting a checkOnly deploy along with a runAllTests test level.  Coverage amounts can be retrieved by using the verbose option with the Deploy command.  

Having the line decorations would be nice.  

- [ ] Use an Text Editor Decoration to highlight the covered lines
https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nametexteditordecorationtypeaspan-classcodeitem-id214texteditordecorationtypespan

- [ ] Show the covered percentage in the status bar item text after a successful deploy.  Use a Timeout of 5 seconds after the successful deployment, then show the percentage covered

- [ ] Use a Editor Title menu to toggle the uncovered/covered line decorations...  
Refer to https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus

**Comment by Telarian** [comment]
@celador I'm not sure if this feature is the reason that coverage information has started appearing in the output upon running tests via the "Run Tests" command, but I think it's a decent bet. I have to say, that thus far, I'm not a fan. You used to get a pretty concise list of the tests and their status including any errors. You still get that, but only after scrolling up for a few hundred lines. I don't think this is improving things. That's my 2¢.

**Comment by celador** [comment]
I appreciate the comment.  This is an early stage of adding line coverage
information in the editor.  It will go away shortly in favor of some nice
subtle line highlighting.
What do you think... Should we highlight the line, in something like a
faint red?  or should we put something in the gutter, maybe a green check
or green dot or something?
Or should we just add Warnings to the code validations? so lines not
covered get an orange or green squiggly?
Thinking about it, I kind of like the validation option... it provides
information to built in tooling instead of just decorating the editor
somehow... But then validations might get overwhelming and noisy...

Also, be on the lookout for code completion coming soon :)  I look forward
to your feedback on that new feature.

**Comment by Telarian** [comment]
@celador I do look forward to the sort of code coverage display you're talking about. That sounds great and would be really useful. I just didn't care much for the intermediate incarnation. I rather like the way that it gets highlighted in opposing colors in the native Salesforce dev console. It works quite nicely. I do think it needs to be a feature you can easily turn on and off, I can see it being rather annoying if that's not what you're focused on at that moment. The only issue I think you might have with using the squiggly validation indications is that it could sort of drown out the other information you're already getting from them.

I look forward to that code completion work you're doing with great anticipation. That will be incredibly helpful. I'm certainly impressed with the work you've done thus far. It's been very helpful.

Just as soon as I think of something useful to tackle that you're not already doing, I'm going to try and jump in and help you as well. Not sure how it will go since my vscode extension experience is non-existent... but I'll try.

**Comment by kbannon** [comment]
I see this feature in the docs. The Toggle Test Coverage is in the top right corner, but the button doesn't seem to do anything. I also get "Test coverage of selected Apex Trigger is 0%, at least 1% test coverage is required" in my output window even though I haven't pulled in a trigger from salesforce.

I have "showTestCoverage": true in my force.json.

I have my test class/test methods in the right pane, and my class in the left pane. I run unit tests, and my tests run successfully. But, code coverage isn't showing anywhere.

Any advice?

OSX: 10.12.3
VSCode: 1.10.2
ForceCode: 0.5.13

**Comment by dabdemon** [comment]
Same than kbannon. Not sure what step I am missing but I'm not even getting the Test Coverage %.
After running unit test for an specific test class I'm getting a full log of all test classes, and the Code Coverage % is not accurate based on what I see on SublimeText + Mavensmate or Developer Console.

Really want to migrate to VSCode and forceCode, and this won't be an stopper, but it will be really useful to have this working to avoid using two different editors.

Win10
VSCode: 1.10.2
ForceCode: 0.5.13

Regards.

**Comment by celador** [comment]
Currently, the code coverage only works for the current test(s)  I need to add the ability to Run All Tests and to have the coverage be a little persistent.

**Comment by brandonmikeska** [comment]
Hmm looks like the code coverage isn't working anymore for me. Is there a way to track down why it's not showing, and why the percentage is off?

**Comment by pauloavelar** [comment]
I started using ForceCode this week after dabbling with half a dozen other IDEs. I am assuming Toggle Test Coverage was supposed to highlight code lines that are currently covered by a test, but I have never got it working (Win10, VSCode x64).

By the way, I have other questions regarding retrieving logs and opening the ForceCode menu when no files are opened. Where is the best place to discuss them?

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dabdemon** [comment]
Hi @celador 

I'm not sure if I understand your comment about "the code coverage onlyworks for the current test(s)".
I am actually running test for a single Test Class and I cannot get the Code Coverage for the associated APEX Class. Even with no code line highlights, to know the % of code coverage is a must.

I'm not sure if I may be missing something here, but any help on how to make this work will be highly appreciated.

Thanks again for your great work on the forceCode extension.
Regards.

**Comment by celador** [comment]
Please use the instructions at the bottom of the Readme to debug the issue.  It would be great if you could create a PR to resolve the issue.
