### ISSUE TITLE
store org credentials in OS keychain

### ISSUE THREAD

**Issue by dshahin** [celador/ForceCode#58]
- [ ] Integrate the keytar library for cross-platform key storage

**Comment by celador** [comment]
This may be done closer to a 1.0 release... 
I've toyed around with doing this in the past, but found it actually made it more difficult on myself as I could no longer be sure which user I was logged in with.  I usually have multiple sets of credentials for a project, with each having a regularly changing the password and/or token.  Insuring I know exactly what credentials are being used is important. The config files provide a handy place to store credential information so I don't waste time searching for my password info.

I understand the concern with security/privacy, but I've found my need to view/check/update my credentials in plaintext overrides whatever security concerns I have.  

Regardless, my wishes for version 1.0 would look like... 

-[] Have a `Switch Credentials` command that would bring up a list of the available logins, along with the final option being `Add New Credentials`

-[] Allow OAuth for logging in and saving credentials

-[] Create a command to show the password, or provide good documentation on how to easily retrieve the password in all three Operating Systems.  Knowing the current password is a fundamental requirement when working with regularly changing passwords and tokens across multiple orgs with the same project.  

-[] Be extra sure it doesn't cause cross-OS issues, since Windows/Linux/OS X stores information in different ways, inconsistencies.  This was one of the reasons it was pulled before.

-[] Possibly move the configuration settings back to the settings.json file (I like being able to easily switch between users by renaming the config files, but if that's not the way it will be done, then having the separate settings file provides less assistance.  Further, as VSCode now has intellisense for config settings, there is more reason to move the settings to the settings.json file)

-[] Improve visual awareness of the currently logged in user.  Print the username to the output channel whenever the login happens.  Show the username at the top of the Menu in the description of the Switch Credentials command.
It has to be as easy to lookup your current user as it is now (just open the force.json file).  I regularly switch users, so knowing the currently logged in user is critical.
