### ISSUE TITLE
ForceCode: No Credentials

### ISSUE THREAD

**Issue by wabbott-veeva** [celador/ForceCode#66]
I go through the usual steps:
1. Please enter your SFDC username. Done
2. Enter password
3. Sandbox
4. Yes (Automatically deploy...)
Shows 'Connected as msadmin@......'

5. Open Salesforce.com files - nothing happens. In the ForceCode bar shows: ForceCode No Credentials

Enter credentials, rinse and repeat.  Same result.

**Comment by wrone** [comment]
i have the same issue :(

**Comment by celador** [comment]
Please provide more details

What OS are you using?
What version is the org that you are using?
Did this org work previously with this extension?

**Comment by celador** [comment]
Can you run this SOQL query in your org?   'SELECT NamespacePrefix FROM Organization' and tell me what happens?

**Comment by celador** [comment]
I put out a new version, 0.4.21  please update and give it a shot.  it will probably still error out, but may provide better information

**Comment by wabbott-veeva** [comment]
Still errors with 'Missing Credentials' (right after you enter your credentials).  No further error messages.  Thanks for trying.

**Comment by wabbott-veeva** [comment]
OS: Win10.  No previous use so can't compare with previous extension.

**Comment by celador** [comment]
I understand what's going on now.  You're getting this error because you do not have a folder open in VSCode.

ForceCode saves your configuration to a force.json file in the folder you have open in VSCode. You have to have a folder open to be able to save the file.  If you don't already have your project saved anywhere, then create a new folder and name it however you want to name your project... Your Salesforce files will live inside a `src` folder in the folder you just created.  Our teams typically start with a Git repo, and then open the menu and it will prompt you for your credentials.  

If you don't have a folder open, VSCode cannot save the configuration file.  So, when you try to do anything, it will not be happy and tell you it can't find your credentials.

This is my fault.  I need to add better documentation on how to get started.
