### ISSUE TITLE
Info on the extension approach

### ISSUE THREAD

**Issue by Telarian** [celador/ForceCode#67]
Hey @celador,

I'm just wondering if you can give me some direction on where to learn more about the approach ForceCode takes in it's architecture? I'm trying to wrap my head around it, but it just seems like there are some big underlying architecture concepts I know nothing about. I believe some of it is probably your DI solution. It's a huge step from the silly little vscode extension samples to what you are doing here. I'm trying to find the information to bridge the gap.

I just thought you might throw out some references where I can see why this is all organized the way it is. I love the end result you have produced, and I would just like to be able to take in some ideas about how to achieve similarly awesome results.

Any insight you could provide would be greatly appreciated.
Thanks

**Comment by celador** [comment]
I haven't forgotten about you.  I am in the process of putting together a documentation site, but that is dragging longer than I expected, so I'll simply reply to you here and use this as the basis for some documentation later.  Forgive me if this is a bit stream-of-consciousness.

Okay... approach in the architecture.. well.. if you learn about how to build a VSCode extension in general.. or at least, if you install the Code yeoman generator, you'll be able to scaffold out a VSCode extension.  That is how this extension got it's foundation.  

The overall idea is that the extension has an activation event.  I set the activation event to be on boot as I'm assuming you want the extension to be available as soon as possible, since you're probably a Salesforce developer if you have this extension installed... So.. activation event... The extension has an activation event, like any application.  Think of the extension.ts activate method as the main method in a C program or index.js in a Node.js program.. it is the default entry point.  

So, the extension activates... when it activates, the Extension initializes itself with some information, specifically, the org's namespace, apex metadata and symbol information about every class in your org.  This process usually just takes a couple seconds.  After that, the main service instance is available at vscode.window.forcecode.  The extension stores most of it's state in that object.  One of the properties is `config` where your configuration json is copied to on every action.

So commands are registered in that activation method.  I have a number of common commands available.  Some commands are only available through the ForceCode menu.  I moved to having actions available primarily through the ForceCode menu, because the options for styling the menu are a little nicer.  So.. most actions live in that ForceCode menu... If you want to contribute to the project, you can put your command either place.

Otherwise, search around for the command you're looking for, inspect the code a bit.  If you're feeling adventurous, press F5 to start the extension and debug a command you are curious about.

Generally speaking, the commands live in the `commands` folder.  There are some providers, one for Salesforce files.. another for Code Completion that I'm working on.

**Comment by Telarian** [comment]
I'm sure my primary issue is just that I don't understand javascript well enough. I come from C# and Apex and I just don't grasp a good deal of the javascript way yet. It seems as though Typescript should actually somewhat ease that burden, but it hasn't really thus far. All the importing and exporting certainly confuses the hell out of me. I don't even know what I was thinking was DI now. Maybe it was the context thing.

The context thing is definitely confusing because it seems like that is all you use in the main file. The "services" concept is also bewildering me for the moment. I get that you've set up Salesforce as a service, but it isn't alone and I don't really understand the others. I was trying to wrap my head around your config code because the way you have set it up seemed really useful for something I had in mind, but I don't really understand what it's doing. I'm sure it is all a good deal more confusing because everything has to await the forceService. Even pulling up the menu is complicated because it's doing so.

So, I take it there was no outline of how to set one of these things set up that you followed. You know, put your commands here. Link them like this. Put your services here. They should be doing this and this. etc. No master plan? Just cut your own path?

I can't even figure out why half of these files exist as they do. I just don't know the convention I suppose, and that's what I'm really wondering about. The silly extension samples aren't enough to need any convention, and your code is but I don't understand the reasons for it all. I get the extension.ts file, but I don't understand why the forceCode.d.ts file exists, or the models/commands.ts file, or why the extension.ts file is so very different from the silly samples.

I'm just struggling to grasp it all. I certainly don't expect you to explain javascript to me. I am slowly coming along on that front. I just am trying to understand the conventions that organize it all the way you have and I'm not succeeding, so I thought any insight you might be able to pass along would be helpful. I'm more than happy to contribute once I understand it and find something that needs doing. I also have a desire to put together another very simple extension for code generation, sort of like Snippets++. Snippet format is painful. I have to write a lot of boilerplate fflib class code and it's driving me bonkers doing it via copy & paste. A lot of the basic structure you're doing like the menu and the status bar and the config stuff would all be really useful in that as well.

So, I'm motivated, I just need to spend more time on it. Your insight is really appreciated.

Thanks,
Tory

**Comment by celador** [comment]
Thank you for the context.  

Typescript is definitely more work to understand than plain ol JavaScript.  JS really only has a few really important principles and everything else follows.  Understand closures and hoisting, and think with functions instead of classes and you'll be fine.  

Typescript is an extremely specific version of JavaScript.  It's extremely similar to ES6, so I would start there if you want to learn Typescript.  TS is basically ES6, but with types, and a type is only the `: foo` bit after any declaration.  So, really, learn ES6 and you should be better.
The importing and exporting, with interfaces and namespaces... It can be a nightmare...Especially because you're really just writing NodeJS code, but in the syntax of ES6... quite confusing sometimes.

Don't worry about any of the files in the Services directory expect for ForceService and Configuration.  I'm not even using logger or operatingSystem anymore and workspace is more of a helper file at this point.  

Here's some context... The extension has an "activation" method that creates the instance of the extension in memory.  That activation method lives in the extension.ts file.  When ForceCode activates, it registers a number of different commands, along with a documentProvider, and a couple event listeners.  Those commands are then registered in VSCode, waiting for someone or something to run them.  Everything in VSCode is event based. 

All the commands live in the commands folder.  So, when you execute a compile command against the currently open file, VSCode runs the force.compile command, which runs the code I wrote in the commands/compile.ts file.

Whenever any command is executed, I retrieve the configuration information, this makes it easy to switch up options.  That is what the configuration service is for.  It retrieves the configuration.  The configuration isn't really a service, more of a helper.  

There was no outline for how to put something like this together.  I ran the `yo code` generator and started with their Hello World extension and just built out from there, command by command, until it is what you see here.  I took the patterns they used in the generated template, but that's about it.

I've gone down a couple dead ends and spun my wheels for a bit, so the state of this project is by no means optimal.  

forcecode.d.ts is a Typescript definition file.  It holds interfaces that are used throughout the extension.  

models/commands.ts defines what is shown in the menu when it opens up.  I didn't like the plain way VSCode runs commands, I wanted icons, so I created a "show menu" command that uses the nicer picklist api.  

There could be a better way to organize the extension.ts file, but it works the way it is, and it's easy enough to copy a line.
