### ISSUE TITLE
After running a failing test i'm not getting what failed

### ISSUE THREAD

**Issue by fricco** [celador/ForceCode#76]
Days ago this was working fine, but now when I run a test and it fails I'm not getting what went wrong. This was really helpful as I'm refactoring test classes and now I have to go back to SFDC to see what went wrong, making the tool useless.
Thanks

**Comment by celador** [comment]
What do you mean when you say "I'm not getting what went wrong" ?  
I made some tweaks to the way tests run in this recent release.
Instead of error validations for failed tests, I return information validations. 

This seemed more appropriate as it wasn't a syntax error.  I was getting mixed up a little bit writing tests the other day, and I wanted it to be clearer to me which error was because of syntax, and what is because of a simple failure.

Also, I tweaked the way the test log works.  It should always display in the third pane.  So, put your test in the first pane, your class in the second, and the logs will show in the third.  That way you can get detailed output and debug information while you're writing the tests.

I am also still outputting the test successes and failures to the output panel.

So, you should be able to get information about your test failures in the editor, in the validations panel, in the output panel, and in the log.

Where were you expecting to get "what went wrong"?

**Comment by fricco** [comment]
@celador before I was seeing the test failuresin the Problems window. Now I don't see anything there, nor in output windows. Where should I see them?
For sure i'm not getting the errors in the editor, nor is  log window being opened. I don't know what is the validations panel as I don't see anything called like that.
The show coverage option is not working at all. As I clicked on the toggle button in the top right is doing nothing.

**Comment by celador** [comment]
You should definitely be seeing the results in the output pane.  Make sure you have the ForceCode output pane visible.  There's a dropdown in the bar where you can switch to different outputs. It might be set to Git or Tasks.

The validations panel... I misspoke, it's actually the "problems" pane. The problems pane should show you information about your failed test

Show coverage only works after you've run a test that touches the class file you have open.  When you select that file, it should show you coverage information.

**Comment by fricco** [comment]
@celador  it was my bad, my output window was showing other addon information. Once I changed it to ForceCode it showed me the failing test with their errors.
Now, problem Window is not showing anything, and the Code Coverage is not working. I have a trigger and handler class opened. And I'm running a test class that is inserting/updating that object, so I expect the trigger and handler class to show the code coverage.

**Comment by celador** [comment]
hmmm... I plan on improving the handling of the coverage soon, but you not receiving any information in the problems pane is concerning to me... 

Do you get compile errors in the editor (the red squigly lines)?

**Comment by fricco** [comment]
@celador No, compilation is successful.

**Comment by celador** [comment]
What version are you using?  latest is 0.5.13

**Comment by fricco** [comment]
@celador yes, i'm in 0.5.13

**Comment by celador** [comment]
Well crap.  I dunno what's going on then.
Can you try to debug it?  https://johnaaronnelson.gitbooks.io/forcecode/#clone-the-repo

**Comment by fricco** [comment]
@celador yep, I will try to follow the steps to debug it and will let you know

**Comment by fricco** [comment]
Ok, i'm stuck in step 3: When running "npm install" it throws an error 'npm' is not recognized as an internal or external command, operable program or batch file. 
This is probably a linux command? What do I need to install in a Windows machine?

**Comment by fricco** [comment]
Sorry for my noob questions :( I was able to install npm.
Now I'm at step 4, starting with F5 but the new VSCode windows is showing an error:
Activating extension `JohnAaronNelson.ForceCode` failed: Cannot find module 'c:/Users/riccomagnofr/Documents/ForceCode/ForceCode/out/src/extension'.

**Comment by celador** [comment]
Good catch. I'll modify the repo. In the meantime, simple create an 'out' folder in the project so it won't complain about the missing folder.

**Comment by fricco** [comment]
@celador I created that folder, but it seems that is looking for a specific file or something in there: Activating extension `JohnAaronNelson.ForceCode` failed: Cannot find module 'c:/Users/riccomagnofr/Documents/ForceCode/ForceCode/out/src/extension'.

**Comment by celador** [comment]
You must have Typescript installed globally.  Try running `npm install typescript -g` and then try debugging the extension again.
