### ISSUE TITLE
retrieve package/metadata

### ISSUE THREAD

**Issue by c-shah** [celador/ForceCode#80]
When I retrieve metadata, it shows error:

![image](https://cloud.githubusercontent.com/assets/12202530/23624618/36caff90-025b-11e7-89ee-28af7a6ebc48.png)

ForceCode: Unexpected token < in JSON as position 6. I have not modified force.json manually nor I find any error in that json. Not sure where the error is coming from.

**Comment by celador** [comment]
Was this command working before?  

Usually when you get that error it means an authentication error.  

I should have some time coming up to work on the extension.  Been swamped with work recently

**Comment by spring-work** [comment]
Yes, it has worked before and I was able to download entire package. it is
also not user/pass issue because user/pass is working fine, and IP is added
to network access, hence there is no need for session token.

I tried it on another, where I downloaded the code from ForceIDE and
ForceCode with same configuration was able to save it just fine, but not
retrieve.
