### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by tnayrb03** [celador/ForceCode#83]
Hello having trouble compiling code, i can compile Apex classes fine upon save but anything in lighting i receive "ForceCode: Unknown Tooling Type. Ensure the body is well formed" I have copied the markup from visual studio and put it directly into the developer console and it compiles fine. This is on Mac

**Comment by Confirm4Crit** [comment]
Gonna throw a couple of notes in here.
I'm having the same issue, I want to note I'm on an older version of VSCODE.

This error that we're seeing is no longer in master branch.
It was removed Feb. 19th:
https://github.com/celador/ForceCode/commit/a2083b549b985bdd0a9cb10186c9d2c35e617d8a#diff-e3bbb2e6fc97a1fdec03340ba2ee3656

I don't know if my extension wasn't properly updated, or if because I'm on an older version of VSCODE, so I'm on an older version of the extension?

I'll give it a look when I get home. I'm on VSCode 1.8.1 if that matters.

**Comment by celador** [comment]
@Confirm4Crit You should definitely upgrade your VSCode.  There were some bugs that were resolved in version 1.9.   There's not much reason not to keep VSCode always upgraded.  Even the insiders build is remarkably stable. And there are awesome new features almost every release.

**Comment by Confirm4Crit** [comment]
For my situation, I don't have the access to update the VSCode, but I did confirm that my home updated VSCode didn't have this issue.
